name: API CI using Gradle

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - "user-interface/**"
  pull_request:
    branches: [ "main" ]
    paths-ignore: 
      - "user-interface/**"

permissions:
  # The Dependency Submission API requires write permission on the repository to submit dependencies
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        dependency-graph: ${{ github.ref == 'refs/heads/main' && 'generate-and-submit' || 'generate' }}

    - name: Gradle build
      run: ./gradlew build

    - name: Jacoco Report to PR
      id: jacoco
      if: github.event_name == 'pull_request'
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: ${{ github.workspace }}/**/build/reports/jacoco/**/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 75
        min-coverage-changed-files: 75
        title: Code Coverage
        update-comment: true
        pass-emoji: ':green_circle:'
        fail-emoji: ':red_circle:'
        debug-mode: true
        skip-if-no-changes: true
