name: Build the Compose test consumer

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "test-consumers/compose/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "test-consumers/compose/**"

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Gradle version
      working-directory: ./test-consumers/compose
      run: ./gradlew --version

    - name: Gradle Java Toolchains
      working-directory: ./test-consumers/compose
      run: ./gradlew -q javaToolchains

    - name: Gradle build
      working-directory: ./test-consumers/compose
      run: ./gradlew build
